name: Run XML and JSON Functional Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  functional-tests:
    permissions:
      id-token: write
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run Functional Tests
        run: mvn -pl ucumate-core -am test -Dgroups=functional-tests
      - name: Report Unit Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: ucumate-core/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
