name: Run XML and JSON Functional Tests

on:
  push:
    branches:
      - main
jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run Functional Tests
        run: mvn -pl ucumate-core -am test -Dgroup=functional-tests
